### ISSUE TITLE
Reference counts and overloaded methods

### ISSUE THREAD

**Issue by mmc41** [kisstkondoros/typelens#17]
Reference counts are not shown correctly in case of overloaded methods (part of a class). In the provided example, it is possible to getPlugin with a one or two ID's. Only the second overload with two ID's is currently used but the reference count is shown above the unused method with only one ID. There should properly be shown distinct reference counts for each method overload. Not sure what to shown for the method implementation at the end. Total references? 

![screen shot 2016-11-19 at 12 55 25](https://cloud.githubusercontent.com/assets/17993/20455239/8c1b6384-ae57-11e6-844c-8f471fbf3289.png)

**Comment by kisstkondoros** [comment]
The extension was built upon the command "vscode.executeReferenceProvider" this gives back literally the same result set as the context menu command "Find All References". Since the result does not contain anything but a URI and a Range object it is not possible to fulfill this request.

Since it is out of the reach of this extension, I'm closing this issue.
