### ISSUE TITLE
performance issues on large source files

### ISSUE THREAD

**Issue by mutsys** [kisstkondoros/typelens#21]
TypeLens causes significant delays and lags in the UI while it is counting references and updating the display when a large file is first opened. This is something of a significant issue particularly when navigating to TypeScript definition files. For some reason, authors of definition files like to create a single monolithic definition per package rather than breaking them up into smaller files per module or group of modules. It would be great to have a configuration here similar to `codemetrics.basics.FileSizeLimitMB` or the ability to exclude files based on a glob/pattern to help remediate this issue.

**Comment by kisstkondoros** [comment]
The sad thing is I have no control over this in this case.
Even if I would introduce a limit for a single file it would only defer the problem since we are talking about references in this case. It's something like a huge graph which has to be traversed, and it does not matter where you start from...
Also I use only the API provided by VSCode to retrieve information from the source files.

BTW once the source graph is loaded by the corresponding language server it should be fast.
Perhaps you can open an issue in the TypeScript and / or in VSCode repo to sign the problem with the performance of the `vscode.executeDocumentSymbolProvider` and `vscode.executeReferenceProvider` commands.

Sorry that I can't help in this case.
