### ISSUE TITLE
Integrate with Angular Language Service

### ISSUE THREAD

**Issue by stephen-nba** [kisstkondoros/typelens#22]
Hi, great extension, would be even better if it worked with Angular templates. I see this has been mentioned before, but now there is an Angular Language Service, maybe this can be revisited?

https://github.com/angular/vscode-ng-language-service

I assume that this somehow uses some metadata that could be used by your plugin. Unfortunately I am not enough of an expert to do this kind of thing!

**Comment by kisstkondoros** [comment]
Hi,

Sorry to say that but I can't do anything about it either ^^

The problem is that Symbol and Reference providers are not exposed, and as I've checked they are actually nonexistent in the vscode-ng-language-service sources.

So it'll be supported when the required services are properly implemented.

some of the related issues at the linked repo:
https://github.com/angular/vscode-ng-language-service/issues/28
https://github.com/angular/vscode-ng-language-service/issues/25
https://github.com/angular/vscode-ng-language-service/issues/29

**Comment by stephen-nba** [comment]
Ok no worries. Hopefully they implement those enhancements soon!
