### ISSUE TITLE
No references from template

### ISSUE THREAD

**Issue by SolArt7** [kisstkondoros/typelens#25]
Your plugin is great!
But there is a problem in angular.
If method was used in html template, reference doesn't indicates.
Thats would be great if you could fix this, thanks!

**Comment by kisstkondoros** [comment]
The extension relies on the API of vscode, especially on a commands `vscode.executeDocumentSymbolProvider` and `vscode.executeReferenceProvider`.
I suppose the latter does not returns usages from html, which is sad, but I can't fix this on my own
I guess the problem might be with
https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/referenceProvider.ts
since it does not considers (IMO) html files as potential source files at all.

**Comment by SolArt7** [comment]
Anyway, thanks guys! You did really useful plugin!

2017-10-01 21:20 GMT+06:00 Tamas Kiss <notifications@github.com>:
