### ISSUE TITLE
Causes runtime issues when installed with Go extension

### ISSUE THREAD

**Issue by Stephn-R** [kisstkondoros/typelens#26]
I noticed my vs-code would reach INSANE memory issues and delays when the TypeLens and Go extensions are installed side by side. Something herein causes the calls to `go tool guru ...` to fail

**Comment by Stephn-R** [comment]
I estimate this is due to you listen to all activation events

**Comment by kisstkondoros** [comment]
Thanks for reporting the issue!

I don't think that it is anyhow related to the activation event, since that only activates the extension itself, not the reference lookup.
For further information please check https://code.visualstudio.com/docs/extensionAPI/activation-events

I suspect that the issue is that the reference provider in https://github.com/Microsoft/vscode-go/blob/master/src/goReferences.ts is forking a new process every time references are requested, and that is for sure a performance killer...

Please report the problem in the repo of vscode-go, until the issue is solved you can exclude go files from being scanned by typelens with the following configuration:
```json
"typelens.skiplanguages": ["go"]
```
BTW: from the code it seems vscode-go also provides an own "reference code lens" implementation, perhaps it is sufficient for your use cases.
