### ISSUE TITLE
Show the reference codelens above decorator in decorated properties

### ISSUE THREAD

**Issue by michaeljota** [kisstkondoros/typelens#38]
Currently the codelens `reference` is showed above the properties, even if they have decorators. This make them hard to read. I would be useful to show the `typelens` above the decorator. 

```ts
// Current
class A {
  @Decorator()
  3 references for property
  public property: string;
}
```

```ts
// Expected
class A {
  3 references for property
  @Decorator()
  public property: string;
}
```

**Comment by kisstkondoros** [comment]
Thanks for the issue report!

As the extension has no knowledge about the AST of the typescript (or any other) file since it operates on the result of the `vscode.executeDocumentSymbolProvider` command I couldn't infer such information.

I'm closing this because the necessary information is not present and hacking it in would make it less maintainable. I'm open for PR's however.
