### ISSUE TITLE
Freezes/Crashes VSCode

### ISSUE THREAD

**Issue by con-ssc** [kisstkondoros/typelens#4]
I tried to use it but it seems to be a bit too much if there are a lot of references in the project. Especially when used with other lenses this leads pretty fast to a crash of vscode. Is it possible to diagnose why exactly vscode is crashing when overwhelmed with references?
I used it with GitLens but also only TypeLens led to a lot of crashes.

**Comment by kisstkondoros** [comment]
Thanks for the issue report!
Could you please be more specific?
I'm interested in: 
- After how much time does it crashes?
- Which file types are in use?
- How big the folder / project is?
- Have you tried another project? Does it crashes there as well?
- Have you tried to disable every other extension but this one?

I suspect either a big memory pressure or memory leak, but during my initial tests with the vscode codebase ~2000 ts files it seems to be just fine.

**Comment by con-ssc** [comment]
Sure. Depending on the amount of functions and references the crash can occur right at the start of vscode.
I only used it in js files.
The file had 2000+ lines, the folder size is about 15MB, the project size is 160MB.
Other projects crash as well.
No I have not, I only tested with no extensions at all.

**Comment by kisstkondoros** [comment]
I had tried to reproduce it by opening the following framework sources
angular 2 - 107 js files ~ 40 mb
dojo -  124 js files ~ 19 mb
jquery - 63 js files ~ 30 mb

> No I have not, I only tested with no extensions at all.
I suppose there might some other extension which either interferes somehow with typelens or causes the issue.

Feel free to reopen if:
-  you can reproduce the issue while only this extension is enabled,
- using a publicly accessible repo - so that I can try to reproduce it using exactly that

Sorry, I've tried it really hard to figure out what's going on, but for me it didn't occurred.
