### ISSUE TITLE
Feature Request: Add specific functions/variables to ignore list.

### ISSUE THREAD

**Issue by ChadESmith42** [kisstkondoros/typelens#41]
This is a great extension.

As a developer, I would like to exclude specific functions and key-words from inclusion in the reference finder.

For example, in Angular, I don't need to find each reference for an ngOnInit() or for a boolean that is used to control toggling HTML features ("public isLoading: boolean;").

![image](https://user-images.githubusercontent.com/39306798/60606076-488bb180-9d80-11e9-9260-cf7541090441.png)

Implementation may look something like this:
"typelens.excludeignoreitemlist": true,
"typelens.ignoritemlist": [ "ngOnInit", "ngOnChanges", "ngOnDestroy", "loading", "show", "hide"]

Thank you for the awesome extension!

**Comment by ctf0** [comment]
maybe having an option to ignore by symbol type would be very helpful as well

**Comment by kisstkondoros** [comment]
@ChadESmith42 
This is basically caused by the fact that you can not limit the scope of the lookup (in this case ngOnint would have exactly 0 reference or at most 1-2 in the angular source files - if they are attached at all) in an ideal world this would be an option for the vscode api command (search for base method / property etc references or the current one only). Having such an exclude list is something I wouldn't prefer as a user, since it could easily exclude interesting things (e.g. show and hide could be many times in a codebase, loading too). I see no elegant solution for this however, so I'm still considering this :unamused: 

@ctf0 what did you meant with `ignore by symbol type`? The set of symbols for which the extension does anything is already limited. Here is the list of the supported SymbolKinds:
`SymbolKind.Method, SymbolKind.Function, SymbolKind.Property, SymbolKind.Class, SymbolKind.Interface`, It's not configurable yet, do you think it would make sense?

**Comment by ctf0** [comment]
@kisstkondoros yes exactly

**Comment by kisstkondoros** [comment]
The new version (typelens@1.8.0) should soon be available in the market. This version will provide additional filtering capabilities:
- for ignoring based on the symbol type
`showReferencesForMethods, showReferencesForFunctions, showReferencesForProperties, showReferencesForClasses, showReferencesForInterfaces`

- for ignoring symbols by name
`ignorelist`
(it's default value is the list of  [angular lifecycle callbacks](https://angular.io/guide/lifecycle-hooks))
